# Site settings
title: Sameer Bhanot's dev blog
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sameer Bhanot
user_description: Having 15+ years of experience in technical industry, I have very good experience of prototyping, designing, development and testing of mobile applications. I have a very good experience of Software development processes.  Software projects constantly change from their primary state or initial idea. So I work in sprints. Over the past years, I have successfully developed and deployed many mobile solutions for clients across the globe. I have been using a lot of good programming practices and patterns, that help me write better code. Most of the applications I have worked on, I have developed from scratch, so I know how to design application architecture and write clean and well-maintained code. Your satisfaction and delivering a quality product are my top priorities.
user_title: Android Developer
email: sam.androiddev@gmail.com
twitter_username: https://twitter.com/SamzDroid
github_username:  https://samzdroid.github.io
gplus_username:  https://plus.google.com/u/2/109868476959388170902

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
